version: '3.8'

services:
  frontend:
    build:
      context: ./source
      dockerfile: Dockerfile
    ports:
      - "808:80"
    restart: unless-stopped
    networks:
      - homni-network

networks:
  homni-network:
    driver: bridge 