version: '3.8'

services:
  homni:
    build: .
    container_name: homni-dashboard
    ports:
      - "808:80"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:80/index.html"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s
